// Code generated by hertz generator.

package synapse4b

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	system "github.com/xh-polaris/synapse4b/biz/api/model/system"
	sysapp "github.com/xh-polaris/synapse4b/biz/application/system"
)

// SendVerifyCode .
// @router /system/send_verify_code [POST]
func SendVerifyCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system.SendVerifyCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp, err := sysapp.SystemSVC.Send(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// CheckVerifyCode .
// @router /system/check_verify_code [POST]
func CheckVerifyCode(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system.CheckVerifyCodeReq
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp, err := sysapp.SystemSVC.Check(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// SignTicket .
// @router /system/sign_ticket [POST]
func SignTicket(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system.SignTicketReq
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp, err := sysapp.SystemSVC.SignTicket(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}

// ExchangeTicket .
// @router /system/exchange_ticket [POST]
func ExchangeTicket(ctx context.Context, c *app.RequestContext) {
	var err error
	var req system.ExchangeTicketReq
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp, err := sysapp.SystemSVC.ExchangeTicket(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}
