// Code generated by hertz generator.

package synapse4b

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	thirdparty "github.com/xh-polaris/synapse4b/biz/api/model/thirdparty"
	tpApp "github.com/xh-polaris/synapse4b/biz/application/thirdparty"
)

// ThirdPartyLogin .
// @router /thirdparty/login [POST]
func ThirdPartyLogin(ctx context.Context, c *app.RequestContext) {
	var err error
	var req thirdparty.ThirdPartyLoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		invalidParamRequestResponse(c, err.Error())
		return
	}

	resp, err := tpApp.ThirdPartySVC.Login(ctx, &req)
	if err != nil {
		internalServerErrorResponse(ctx, c, err)
		return
	}
	c.JSON(consts.StatusOK, resp)
}
