// Code generated by hertz generator.

package synapse4b

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basic_userMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicuserloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicuserregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _basicuserresetpasswordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _systemMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _checkverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _exchangeticketMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sendverifycodeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _signticketMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _thirdpartyMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _thirdpartyloginMw() []app.HandlerFunc {
	// your code...
	return nil
}
