// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"github.com/xh-polaris/synapse4b/biz/domain/basicuser/dal/model"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newUnit(db *gorm.DB, opts ...gen.DOOption) unit {
	_unit := unit{}

	_unit.unitDo.UseDB(db, opts...)
	_unit.unitDo.UseModel(&model.Unit{})

	tableName := _unit.unitDo.TableName()
	_unit.ALL = field.NewAsterisk(tableName)
	_unit.ID = field.NewField(tableName, "id")
	_unit.Name = field.NewString(tableName, "name")
	_unit.Extra = field.NewField(tableName, "extra")
	_unit.CreatedAt = field.NewInt64(tableName, "created_at")
	_unit.UpdatedAt = field.NewInt64(tableName, "updated_at")
	_unit.DeletedAt = field.NewField(tableName, "deleted_at")

	_unit.fillFieldMap()

	return _unit
}

type unit struct {
	unitDo unitDo

	ALL       field.Asterisk
	ID        field.Field
	Name      field.String // Unit Name
	Extra     field.Field
	CreatedAt field.Int64
	UpdatedAt field.Int64
	DeletedAt field.Field

	fieldMap map[string]field.Expr
}

func (u unit) Table(newTableName string) *unit {
	u.unitDo.UseTable(newTableName)
	return u.updateTableName(newTableName)
}

func (u unit) As(alias string) *unit {
	u.unitDo.DO = *(u.unitDo.As(alias).(*gen.DO))
	return u.updateTableName(alias)
}

func (u *unit) updateTableName(table string) *unit {
	u.ALL = field.NewAsterisk(table)
	u.ID = field.NewField(table, "id")
	u.Name = field.NewString(table, "name")
	u.Extra = field.NewField(table, "extra")
	u.CreatedAt = field.NewInt64(table, "created_at")
	u.UpdatedAt = field.NewInt64(table, "updated_at")
	u.DeletedAt = field.NewField(table, "deleted_at")

	u.fillFieldMap()

	return u
}

func (u *unit) WithContext(ctx context.Context) IUnitDo { return u.unitDo.WithContext(ctx) }

func (u unit) TableName() string { return u.unitDo.TableName() }

func (u unit) Alias() string { return u.unitDo.Alias() }

func (u unit) Columns(cols ...field.Expr) gen.Columns { return u.unitDo.Columns(cols...) }

func (u *unit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := u.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (u *unit) fillFieldMap() {
	u.fieldMap = make(map[string]field.Expr, 6)
	u.fieldMap["id"] = u.ID
	u.fieldMap["name"] = u.Name
	u.fieldMap["extra"] = u.Extra
	u.fieldMap["created_at"] = u.CreatedAt
	u.fieldMap["updated_at"] = u.UpdatedAt
	u.fieldMap["deleted_at"] = u.DeletedAt
}

func (u unit) clone(db *gorm.DB) unit {
	u.unitDo.ReplaceConnPool(db.Statement.ConnPool)
	return u
}

func (u unit) replaceDB(db *gorm.DB) unit {
	u.unitDo.ReplaceDB(db)
	return u
}

type unitDo struct{ gen.DO }

type IUnitDo interface {
	gen.SubQuery
	Debug() IUnitDo
	WithContext(ctx context.Context) IUnitDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IUnitDo
	WriteDB() IUnitDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IUnitDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IUnitDo
	Not(conds ...gen.Condition) IUnitDo
	Or(conds ...gen.Condition) IUnitDo
	Select(conds ...field.Expr) IUnitDo
	Where(conds ...gen.Condition) IUnitDo
	Order(conds ...field.Expr) IUnitDo
	Distinct(cols ...field.Expr) IUnitDo
	Omit(cols ...field.Expr) IUnitDo
	Join(table schema.Tabler, on ...field.Expr) IUnitDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IUnitDo
	RightJoin(table schema.Tabler, on ...field.Expr) IUnitDo
	Group(cols ...field.Expr) IUnitDo
	Having(conds ...gen.Condition) IUnitDo
	Limit(limit int) IUnitDo
	Offset(offset int) IUnitDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IUnitDo
	Unscoped() IUnitDo
	Create(values ...*model.Unit) error
	CreateInBatches(values []*model.Unit, batchSize int) error
	Save(values ...*model.Unit) error
	First() (*model.Unit, error)
	Take() (*model.Unit, error)
	Last() (*model.Unit, error)
	Find() ([]*model.Unit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Unit, err error)
	FindInBatches(result *[]*model.Unit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Unit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IUnitDo
	Assign(attrs ...field.AssignExpr) IUnitDo
	Joins(fields ...field.RelationField) IUnitDo
	Preload(fields ...field.RelationField) IUnitDo
	FirstOrInit() (*model.Unit, error)
	FirstOrCreate() (*model.Unit, error)
	FindByPage(offset int, limit int) (result []*model.Unit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IUnitDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (u unitDo) Debug() IUnitDo {
	return u.withDO(u.DO.Debug())
}

func (u unitDo) WithContext(ctx context.Context) IUnitDo {
	return u.withDO(u.DO.WithContext(ctx))
}

func (u unitDo) ReadDB() IUnitDo {
	return u.Clauses(dbresolver.Read)
}

func (u unitDo) WriteDB() IUnitDo {
	return u.Clauses(dbresolver.Write)
}

func (u unitDo) Session(config *gorm.Session) IUnitDo {
	return u.withDO(u.DO.Session(config))
}

func (u unitDo) Clauses(conds ...clause.Expression) IUnitDo {
	return u.withDO(u.DO.Clauses(conds...))
}

func (u unitDo) Returning(value interface{}, columns ...string) IUnitDo {
	return u.withDO(u.DO.Returning(value, columns...))
}

func (u unitDo) Not(conds ...gen.Condition) IUnitDo {
	return u.withDO(u.DO.Not(conds...))
}

func (u unitDo) Or(conds ...gen.Condition) IUnitDo {
	return u.withDO(u.DO.Or(conds...))
}

func (u unitDo) Select(conds ...field.Expr) IUnitDo {
	return u.withDO(u.DO.Select(conds...))
}

func (u unitDo) Where(conds ...gen.Condition) IUnitDo {
	return u.withDO(u.DO.Where(conds...))
}

func (u unitDo) Order(conds ...field.Expr) IUnitDo {
	return u.withDO(u.DO.Order(conds...))
}

func (u unitDo) Distinct(cols ...field.Expr) IUnitDo {
	return u.withDO(u.DO.Distinct(cols...))
}

func (u unitDo) Omit(cols ...field.Expr) IUnitDo {
	return u.withDO(u.DO.Omit(cols...))
}

func (u unitDo) Join(table schema.Tabler, on ...field.Expr) IUnitDo {
	return u.withDO(u.DO.Join(table, on...))
}

func (u unitDo) LeftJoin(table schema.Tabler, on ...field.Expr) IUnitDo {
	return u.withDO(u.DO.LeftJoin(table, on...))
}

func (u unitDo) RightJoin(table schema.Tabler, on ...field.Expr) IUnitDo {
	return u.withDO(u.DO.RightJoin(table, on...))
}

func (u unitDo) Group(cols ...field.Expr) IUnitDo {
	return u.withDO(u.DO.Group(cols...))
}

func (u unitDo) Having(conds ...gen.Condition) IUnitDo {
	return u.withDO(u.DO.Having(conds...))
}

func (u unitDo) Limit(limit int) IUnitDo {
	return u.withDO(u.DO.Limit(limit))
}

func (u unitDo) Offset(offset int) IUnitDo {
	return u.withDO(u.DO.Offset(offset))
}

func (u unitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IUnitDo {
	return u.withDO(u.DO.Scopes(funcs...))
}

func (u unitDo) Unscoped() IUnitDo {
	return u.withDO(u.DO.Unscoped())
}

func (u unitDo) Create(values ...*model.Unit) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Create(values)
}

func (u unitDo) CreateInBatches(values []*model.Unit, batchSize int) error {
	return u.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (u unitDo) Save(values ...*model.Unit) error {
	if len(values) == 0 {
		return nil
	}
	return u.DO.Save(values)
}

func (u unitDo) First() (*model.Unit, error) {
	if result, err := u.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Unit), nil
	}
}

func (u unitDo) Take() (*model.Unit, error) {
	if result, err := u.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Unit), nil
	}
}

func (u unitDo) Last() (*model.Unit, error) {
	if result, err := u.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Unit), nil
	}
}

func (u unitDo) Find() ([]*model.Unit, error) {
	result, err := u.DO.Find()
	return result.([]*model.Unit), err
}

func (u unitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Unit, err error) {
	buf := make([]*model.Unit, 0, batchSize)
	err = u.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (u unitDo) FindInBatches(result *[]*model.Unit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return u.DO.FindInBatches(result, batchSize, fc)
}

func (u unitDo) Attrs(attrs ...field.AssignExpr) IUnitDo {
	return u.withDO(u.DO.Attrs(attrs...))
}

func (u unitDo) Assign(attrs ...field.AssignExpr) IUnitDo {
	return u.withDO(u.DO.Assign(attrs...))
}

func (u unitDo) Joins(fields ...field.RelationField) IUnitDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Joins(_f))
	}
	return &u
}

func (u unitDo) Preload(fields ...field.RelationField) IUnitDo {
	for _, _f := range fields {
		u = *u.withDO(u.DO.Preload(_f))
	}
	return &u
}

func (u unitDo) FirstOrInit() (*model.Unit, error) {
	if result, err := u.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Unit), nil
	}
}

func (u unitDo) FirstOrCreate() (*model.Unit, error) {
	if result, err := u.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Unit), nil
	}
}

func (u unitDo) FindByPage(offset int, limit int) (result []*model.Unit, count int64, err error) {
	result, err = u.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = u.Offset(-1).Limit(-1).Count()
	return
}

func (u unitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = u.Count()
	if err != nil {
		return
	}

	err = u.Offset(offset).Limit(limit).Scan(result)
	return
}

func (u unitDo) Scan(result interface{}) (err error) {
	return u.DO.Scan(result)
}

func (u unitDo) Delete(models ...*model.Unit) (result gen.ResultInfo, err error) {
	return u.DO.Delete(models)
}

func (u *unitDo) withDO(do gen.Dao) *unitDo {
	u.DO = *do.(*gen.DO)
	return u
}
