// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package basicuser

import (
	"context"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/xh-polaris/synapse4b/biz/api/model/thirdparty"
)

type ThirdPartyService interface {
	ThirdPartyLogin(ctx context.Context, req *thirdparty.ThirdPartyLoginReq) (r *thirdparty.ThirdPartyLoginResp, err error)
}

type ThirdPartyServiceClient struct {
	c thrift.TClient
}

func NewThirdPartyServiceClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *ThirdPartyServiceClient {
	return &ThirdPartyServiceClient{
		c: thrift.NewTStandardClient(f.GetProtocol(t), f.GetProtocol(t)),
	}
}

func NewThirdPartyServiceClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *ThirdPartyServiceClient {
	return &ThirdPartyServiceClient{
		c: thrift.NewTStandardClient(iprot, oprot),
	}
}

func NewThirdPartyServiceClient(c thrift.TClient) *ThirdPartyServiceClient {
	return &ThirdPartyServiceClient{
		c: c,
	}
}

func (p *ThirdPartyServiceClient) Client_() thrift.TClient {
	return p.c
}

func (p *ThirdPartyServiceClient) ThirdPartyLogin(ctx context.Context, req *thirdparty.ThirdPartyLoginReq) (r *thirdparty.ThirdPartyLoginResp, err error) {
	var _args ThirdPartyServiceThirdPartyLoginArgs
	_args.Req = req
	var _result ThirdPartyServiceThirdPartyLoginResult
	if err = p.Client_().Call(ctx, "ThirdPartyLogin", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

type ThirdPartyServiceProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      ThirdPartyService
}

func (p *ThirdPartyServiceProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *ThirdPartyServiceProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *ThirdPartyServiceProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewThirdPartyServiceProcessor(handler ThirdPartyService) *ThirdPartyServiceProcessor {
	self := &ThirdPartyServiceProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self.AddToProcessorMap("ThirdPartyLogin", &thirdPartyServiceProcessorThirdPartyLogin{handler: handler})
	return self
}
func (p *ThirdPartyServiceProcessor) Process(ctx context.Context, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(ctx, seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush(ctx)
	return false, x
}

type thirdPartyServiceProcessorThirdPartyLogin struct {
	handler ThirdPartyService
}

func (p *thirdPartyServiceProcessorThirdPartyLogin) Process(ctx context.Context, seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := ThirdPartyServiceThirdPartyLoginArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("ThirdPartyLogin", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return false, err
	}

	iprot.ReadMessageEnd()
	var err2 error
	result := ThirdPartyServiceThirdPartyLoginResult{}
	var retval *thirdparty.ThirdPartyLoginResp
	if retval, err2 = p.handler.ThirdPartyLogin(ctx, args.Req); err2 != nil {
		x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing ThirdPartyLogin: "+err2.Error())
		oprot.WriteMessageBegin("ThirdPartyLogin", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush(ctx)
		return true, err2
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("ThirdPartyLogin", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(ctx); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type ThirdPartyServiceThirdPartyLoginArgs struct {
	Req *thirdparty.ThirdPartyLoginReq `thrift:"req,1"`
}

func NewThirdPartyServiceThirdPartyLoginArgs() *ThirdPartyServiceThirdPartyLoginArgs {
	return &ThirdPartyServiceThirdPartyLoginArgs{}
}

func (p *ThirdPartyServiceThirdPartyLoginArgs) InitDefault() {
}

var ThirdPartyServiceThirdPartyLoginArgs_Req_DEFAULT *thirdparty.ThirdPartyLoginReq

func (p *ThirdPartyServiceThirdPartyLoginArgs) GetReq() (v *thirdparty.ThirdPartyLoginReq) {
	if !p.IsSetReq() {
		return ThirdPartyServiceThirdPartyLoginArgs_Req_DEFAULT
	}
	return p.Req
}

var fieldIDToName_ThirdPartyServiceThirdPartyLoginArgs = map[int16]string{
	1: "req",
}

func (p *ThirdPartyServiceThirdPartyLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *ThirdPartyServiceThirdPartyLoginArgs) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField1(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ThirdPartyServiceThirdPartyLoginArgs[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ThirdPartyServiceThirdPartyLoginArgs) ReadField1(iprot thrift.TProtocol) error {
	_field := thirdparty.NewThirdPartyLoginReq()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Req = _field
	return nil
}

func (p *ThirdPartyServiceThirdPartyLoginArgs) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("ThirdPartyLogin_args"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField1(oprot); err != nil {
			fieldId = 1
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ThirdPartyServiceThirdPartyLoginArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err = oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		goto WriteFieldBeginError
	}
	if err := p.Req.Write(oprot); err != nil {
		return err
	}
	if err = oprot.WriteFieldEnd(); err != nil {
		goto WriteFieldEndError
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 1 end error: ", p), err)
}

func (p *ThirdPartyServiceThirdPartyLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ThirdPartyServiceThirdPartyLoginArgs(%+v)", *p)

}

type ThirdPartyServiceThirdPartyLoginResult struct {
	Success *thirdparty.ThirdPartyLoginResp `thrift:"success,0,optional"`
}

func NewThirdPartyServiceThirdPartyLoginResult() *ThirdPartyServiceThirdPartyLoginResult {
	return &ThirdPartyServiceThirdPartyLoginResult{}
}

func (p *ThirdPartyServiceThirdPartyLoginResult) InitDefault() {
}

var ThirdPartyServiceThirdPartyLoginResult_Success_DEFAULT *thirdparty.ThirdPartyLoginResp

func (p *ThirdPartyServiceThirdPartyLoginResult) GetSuccess() (v *thirdparty.ThirdPartyLoginResp) {
	if !p.IsSetSuccess() {
		return ThirdPartyServiceThirdPartyLoginResult_Success_DEFAULT
	}
	return p.Success
}

var fieldIDToName_ThirdPartyServiceThirdPartyLoginResult = map[int16]string{
	0: "success",
}

func (p *ThirdPartyServiceThirdPartyLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *ThirdPartyServiceThirdPartyLoginResult) Read(iprot thrift.TProtocol) (err error) {

	var fieldTypeId thrift.TType
	var fieldId int16

	if _, err = iprot.ReadStructBegin(); err != nil {
		goto ReadStructBeginError
	}

	for {
		_, fieldTypeId, fieldId, err = iprot.ReadFieldBegin()
		if err != nil {
			goto ReadFieldBeginError
		}
		if fieldTypeId == thrift.STOP {
			break
		}

		switch fieldId {
		case 0:
			if fieldTypeId == thrift.STRUCT {
				if err = p.ReadField0(iprot); err != nil {
					goto ReadFieldError
				}
			} else if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		default:
			if err = iprot.Skip(fieldTypeId); err != nil {
				goto SkipFieldError
			}
		}
		if err = iprot.ReadFieldEnd(); err != nil {
			goto ReadFieldEndError
		}
	}
	if err = iprot.ReadStructEnd(); err != nil {
		goto ReadStructEndError
	}

	return nil
ReadStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read struct begin error: ", p), err)
ReadFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d begin error: ", p, fieldId), err)
ReadFieldError:
	return thrift.PrependError(fmt.Sprintf("%T read field %d '%s' error: ", p, fieldId, fieldIDToName_ThirdPartyServiceThirdPartyLoginResult[fieldId]), err)
SkipFieldError:
	return thrift.PrependError(fmt.Sprintf("%T field %d skip type %d error: ", p, fieldId, fieldTypeId), err)

ReadFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T read field end error", p), err)
ReadStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
}

func (p *ThirdPartyServiceThirdPartyLoginResult) ReadField0(iprot thrift.TProtocol) error {
	_field := thirdparty.NewThirdPartyLoginResp()
	if err := _field.Read(iprot); err != nil {
		return err
	}
	p.Success = _field
	return nil
}

func (p *ThirdPartyServiceThirdPartyLoginResult) Write(oprot thrift.TProtocol) (err error) {
	var fieldId int16
	if err = oprot.WriteStructBegin("ThirdPartyLogin_result"); err != nil {
		goto WriteStructBeginError
	}
	if p != nil {
		if err = p.writeField0(oprot); err != nil {
			fieldId = 0
			goto WriteFieldError
		}
	}
	if err = oprot.WriteFieldStop(); err != nil {
		goto WriteFieldStopError
	}
	if err = oprot.WriteStructEnd(); err != nil {
		goto WriteStructEndError
	}
	return nil
WriteStructBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
WriteFieldError:
	return thrift.PrependError(fmt.Sprintf("%T write field %d error: ", p, fieldId), err)
WriteFieldStopError:
	return thrift.PrependError(fmt.Sprintf("%T write field stop error: ", p), err)
WriteStructEndError:
	return thrift.PrependError(fmt.Sprintf("%T write struct end error: ", p), err)
}

func (p *ThirdPartyServiceThirdPartyLoginResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err = oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			goto WriteFieldBeginError
		}
		if err := p.Success.Write(oprot); err != nil {
			return err
		}
		if err = oprot.WriteFieldEnd(); err != nil {
			goto WriteFieldEndError
		}
	}
	return nil
WriteFieldBeginError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 begin error: ", p), err)
WriteFieldEndError:
	return thrift.PrependError(fmt.Sprintf("%T write field 0 end error: ", p), err)
}

func (p *ThirdPartyServiceThirdPartyLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ThirdPartyServiceThirdPartyLoginResult(%+v)", *p)

}
